#!/usr/bin/env python3
"""
Run end-to-end release preparation without git tag/push.

Pipeline:
  1) Optional semantic version bump
  2) Release preparation checks
  3) Final summary (release notes already generated by release_prep.py)

Usage:
  python scripts/release_all_in_one.py
  python scripts/release_all_in_one.py --bump patch
  python scripts/release_all_in_one.py --bump minor --full
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_PATH = ROOT / "VERSION"


def _run(cmd: list[str]) -> int:
    print(f"> {' '.join(cmd)}")
    r = subprocess.run(cmd, cwd=str(ROOT))
    return int(r.returncode)


def _read_version(default: str = "0.0.0-dev") -> str:
    try:
        value = VERSION_PATH.read_text(encoding="utf-8").strip()
    except OSError:
        return default
    return value or default


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bump", choices=["major", "minor", "patch"], default="", help="Optional semantic bump before checks.")
    ap.add_argument("--full", action="store_true", help="Run network-aware checks via release_prep --full.")
    args = ap.parse_args()

    before_version = _read_version()
    if args.bump:
        rc = _run([sys.executable, str(ROOT / "scripts" / "bump_version.py"), args.bump])
        if rc != 0:
            return rc

    prep_cmd = [sys.executable, str(ROOT / "scripts" / "release_prep.py")]
    if args.full:
        prep_cmd.append("--full")
    rc_prep = _run(prep_cmd)
    if rc_prep != 0:
        return rc_prep

    after_version = _read_version()
    if not after_version or after_version == "0.0.0-dev":
        print("ERROR: VERSION is missing or invalid.")
        return 2

    print("\nAll-in-one release prep finished.")
    print(f"Version before: {before_version}")
    print(f"Version now:    {after_version}")
    print("No git tag/push executed.")
    print("If everything looks good:")
    print(f"  git tag v{after_version}")
    print("  git push origin --tags")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

